import gradio as gr
import numpy as np
from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

# Load the BLIP model and processor
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# Define the function to generate captions from images
'''
image: np.ndarray is a type hint for the parameter image.

It means the function expects image to be a NumPy array (numpy.ndarray), 
usually pixel data like H x W x C.

It improves readability, editor autocomplete, and static type checking.
It does not enforce the type at runtime by itself—Python will still run 
unless you add explicit checks.
'''
def generate_caption(image: np.ndarray):

    # Convert the NumPy array to a PIL Image and ensure it's in RGB format
    image2 = Image.fromarray(image).convert('RGB')

    # Process the input image
    inputs = processor(image2, "the image of", return_tensors="pt")
    
    # Generate caption using the model
    out = model.generate(**inputs, max_length=50)
    
    # Decode the generated caption
    caption = processor.decode(out[0], skip_special_tokens=True)
    
    return caption

# Create the Gradio interface
iface = gr.Interface(fn=generate_caption, inputs=gr.Image(type="numpy"), 
                     outputs="text", title="Image Captioning with BLIP",
                     description="Upload an image and get a caption generated by the BLIP model.")

# Launch the Gradio app
iface.launch()